import fs from 'node:fs';
import path from 'node:path';

/**
 * Pi's extension event stream is the source of task activity. The extension
 * sends only the latest pending event so a slow/restarting terminal server
 * cannot block or backlog the Agent process.
 */
export const PI_STATUS_EXTENSION_SOURCE = String.raw`// Generated by Bohemian Agent Control. Do not edit.
const timeoutMs = 1000;
let socket;
let reconnectTimer;
let active = false;
let pending = null;
let sessionId = '';
let agentEndReported = false;
let settledSupported = false;
let pendingEndTimer = null;
let pendingEndContext = null;
let endRecheckMs = 25;

function hookEnv() {
  return {
    wsUrl: process.env.BOHEMIAN_TERMINAL_WS_URL,
    terminalId: process.env.BOHEMIAN_TERMINAL_ID,
    launchToken: process.env.BOHEMIAN_AGENT_LAUNCH_TOKEN,
    token: process.env.BOHEMIAN_TERMINAL_TOKEN,
  };
}

function metadata(ctx) {
  const manager = ctx?.sessionManager;
  const value = manager?.getSessionId?.();
  if (typeof value === 'string' && value) sessionId = value;
}

function enqueue(state, extra = {}) {
  const env = hookEnv();
  if (!env.wsUrl || !env.terminalId || !env.launchToken || !env.token) return;
  pending = {
    type: 'agent-status',
    terminalId: env.terminalId,
    launchToken: env.launchToken,
    payload: { state, providerSessionId: sessionId || undefined, ...extra },
  };
  drain();
}

function connect() {
  const env = hookEnv();
  if (!env.wsUrl || !env.token || typeof WebSocket !== 'function') return;
  if (socket && (socket.readyState === 0 || socket.readyState === 1)) return;
  try {
    socket = new WebSocket(env.wsUrl + '?token=' + encodeURIComponent(env.token));
    socket.addEventListener('open', drain);
    socket.addEventListener('close', () => {
      socket = undefined;
      if (pending && !reconnectTimer) {
        reconnectTimer = setTimeout(() => {
          reconnectTimer = undefined;
          connect();
        }, 250);
        reconnectTimer.unref?.();
      }
    });
    socket.addEventListener('error', () => {});
  } catch {}
}

function drain() {
  if (active || !pending) return;
  connect();
  if (!socket || socket.readyState !== 1) return;
  const next = pending;
  pending = null;
  active = true;
  try {
    socket.send(JSON.stringify(next));
  } catch {
    pending = next;
  }
  setTimeout(() => {
    active = false;
    drain();
  }, timeoutMs).unref?.();
}

function clearEndCheck() {
  if (pendingEndTimer) clearTimeout(pendingEndTimer);
  pendingEndTimer = null;
  pendingEndContext = null;
}

function postEndOnce() {
  if (agentEndReported) return;
  agentEndReported = true;
  enqueue('done');
}

function checkPendingEnd() {
  pendingEndTimer = null;
  const ctx = pendingEndContext;
  if (!ctx || settledSupported || agentEndReported) {
    pendingEndContext = null;
    return;
  }
  try {
    if (typeof ctx.isIdle === 'function' && ctx.isIdle()) {
      pendingEndContext = null;
      postEndOnce();
      return;
    }
  } catch {
    pendingEndContext = null;
    return;
  }
  pendingEndTimer = setTimeout(checkPendingEnd, endRecheckMs);
  pendingEndTimer.unref?.();
  endRecheckMs = Math.min(endRecheckMs * 2, 250);
}

export default function (pi) {
  pi.on('session_start', (_event, ctx) => {
    clearEndCheck();
    agentEndReported = false;
    metadata(ctx);
    enqueue('done', {
      providerEvent: 'session_start',
      sessionSource: 'session_start',
      sessionTransition: true,
    });
  });
  pi.on('before_agent_start', (_event, ctx) => {
    metadata(ctx);
    enqueue('working');
  });
  pi.on('agent_start', (_event, ctx) => {
    metadata(ctx);
    clearEndCheck();
    agentEndReported = false;
    enqueue('working');
  });
  pi.on('tool_execution_start', (event, ctx) => {
    metadata(ctx);
    enqueue('working', { toolName: event.toolName, toolInput: JSON.stringify(event.args ?? {}) });
  });
  pi.on('tool_call', (event, ctx) => {
    metadata(ctx);
    enqueue('working', { toolName: event.toolName, toolInput: JSON.stringify(event.input ?? {}) });
  });
  pi.on('tool_approval_requested', (event, ctx) => {
    metadata(ctx);
    enqueue('waiting', { toolName: event.toolName, prompt: event.reason });
  });
  pi.on('ui_prompt_start', (event, ctx) => {
    metadata(ctx);
    enqueue('waiting', { prompt: event?.title });
  });
  pi.on('ui_prompt_end', (_event, ctx) => {
    metadata(ctx);
    if (typeof ctx?.isIdle === 'function' && ctx.isIdle()) postEndOnce();
    else enqueue('working');
  });
  pi.on('session_shutdown', (_event, ctx) => {
    metadata(ctx);
    postEndOnce();
  });
  pi.on('agent_settled', (_event, ctx) => {
    metadata(ctx);
    settledSupported = true;
    clearEndCheck();
    postEndOnce();
  });
  pi.on('agent_end', (event, ctx) => {
    metadata(ctx);
    if (event?.willContinue === true) {
      clearEndCheck();
      return;
    }
    if (settledSupported) return;
    if (!ctx || typeof ctx.isIdle !== 'function') {
      postEndOnce();
      return;
    }
    clearEndCheck();
    endRecheckMs = 25;
    pendingEndContext = ctx;
    queueMicrotask(checkPendingEnd);
  });
}
`;

/** Write the generated bridge into the terminal server's runtime directory. */
export function writePiStatusExtension(directory: string): string {
  const target = path.join(directory, 'bohemian-agent-status.js');
  try {
    fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== PI_STATUS_EXTENSION_SOURCE) {
      fs.writeFileSync(target, PI_STATUS_EXTENSION_SOURCE, { encoding: 'utf8', mode: 0o600 });
    }
  } catch (error) {
    throw new Error(`Pi status extension unavailable: ${error instanceof Error ? error.message : String(error)}`);
  }
  return target;
}

